# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: op-cdtr

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: op-cdtr
    main: ./cmd/op-cdtr
    binary: op-cdtr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitSHA={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-{{ .ShortCommit }}"

dockers_v2:
  - images:
      - golemnetwork/op-cdtr
    dockerfile: "Dockerfile"
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{ .Version }}"
      - "{{ if not .IsSnapshot }}{{ .Tag }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}.{{ .Minor }}{{ end }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
      - "{{ if .IsSnapshot }}snapshot{{ end }}"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
    build_args:
      VERSION: "{{.Version}}"
      GIT_COMMIT: "{{.Commit}}"

sboms:
  - artifacts: archive
    id: archive
    documents:
      - "${artifact}.sbom.json"
  - artifacts: package
    id: package
    documents:
      - "${artifact}.sbom.json"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^test:"
      - "^build:"

release:
  github:
    owner: arkiv-network
    name: op-cdtr

  header: |
    ## op-cdtr {{ .Tag }}

    Pre-configure Raft state for Optimism conductor to eliminate bootstrap sequencer requirements.

    ### Installation

    #### Binary

    Download the appropriate binary for your platform from the assets below.

    #### Docker

    ```bash
    docker pull golemnetwork/op-cdtr:{{ .Tag }}
    ```

    #### Configuration

    See the README for detailed setup instructions.

  draft: false
  prerelease: auto
